export function createLevelPresets(seedBase) {
  return [
    {
      id: 1,
      difficultyTier: 'intro',
      seedBase: seedBase + 1,
      elementCount: 6,
      piecesPerElement: 3,
      layers: 2,
      density: 'low',
      targetPassRate: 0.95,
      targetDurationSec: [90, 150],
    },
    {
      id: 2,
      difficultyTier: 'warmup',
      seedBase: seedBase + 2,
      elementCount: 7,
      piecesPerElement: 3,
      layers: 2,
      density: 'low',
      targetPassRate: 0.9,
      targetDurationSec: [100, 160],
    },
    {
      id: 3,
      difficultyTier: 'ramp',
      seedBase: seedBase + 3,
      elementCount: 8,
      piecesPerElement: 3,
      layers: 3,
      density: 'medium',
      targetPassRate: 0.8,
      targetDurationSec: [120, 180],
    },
    {
      id: 4,
      difficultyTier: 'mid',
      seedBase: seedBase + 4,
      elementCount: 9,
      piecesPerElement: 3,
      layers: 3,
      density: 'medium',
      targetPassRate: 0.7,
      targetDurationSec: [130, 190],
    },
    {
      id: 5,
      difficultyTier: 'hard',
      seedBase: seedBase + 5,
      elementCount: 10,
      piecesPerElement: 3,
      layers: 4,
      density: 'medium_high',
      targetPassRate: 0.6,
      targetDurationSec: [150, 220],
    },
    {
      id: 6,
      difficultyTier: 'boss',
      seedBase: seedBase + 6,
      elementCount: 10,
      piecesPerElement: [3, 3, 3, 3, 3, 6, 3, 3, 3, 3],
      layers: 4,
      density: 'high',
      targetPassRate: 0.55,
      targetDurationSec: [180, 260],
    },
  ]
}
