module.exports = {
  id: 'beijing',
  contentVersion: 1,
  continentId: 'asia',
  sortOrder: 1,
  unlockAfterCityId: null,
  bundle: {
    packId: 'main',
    preload: 'startup',
  },
  display: {
    name: '北京',
    nameEn: 'Beijing',
    bgColor: '#CC2936',
    tagline: '天安门前看猫猫',
    funFact: '北京是世界上拥有最多宫殿的城市',
  },
  cover: {
    catImage: 'images/cats/cat_beijing.png',
    catThumb: 'images/cats/cat_beijing_thumb.png',
    shareAccent: '#F6D365',
  },
  cat: {
    id: 'cat_beijing',
    name: '京京',
    intro: '戴虎头帽的橘猫，最爱在胡同里晒太阳',
    baseColor: '#F28C28',
    pattern: 'tabby',
    patternColor: '#D4761A',
    accessory: '虎头帽',
    expression: 'smile',
  },
  passport: {
    stampId: 'stamp_beijing',
    stampLabel: '北京',
  },
  elements: [
    { id: 'beijing_01', name: '糖葫芦', category: 'food', rarity: 'core', image: 'images/elements/beijing/beijing_01.png', tags: ['sweet', 'street-food', 'red'] },
    { id: 'beijing_02', name: '京剧脸谱', category: 'culture', rarity: 'core', image: 'images/elements/beijing/beijing_02.png', tags: ['opera', 'mask', 'colorful'] },
    { id: 'beijing_03', name: '天安门', category: 'landmark', rarity: 'core', image: 'images/elements/beijing/beijing_03.png', tags: ['building', 'red', 'iconic'] },
    { id: 'beijing_04', name: '烤鸭', category: 'food', rarity: 'core', image: 'images/elements/beijing/beijing_04.png', tags: ['meat', 'famous', 'golden'] },
    { id: 'beijing_05', name: '兔儿爷', category: 'culture', rarity: 'core', image: 'images/elements/beijing/beijing_05.png', tags: ['toy', 'festival', 'rabbit'] },
    { id: 'beijing_06', name: '长城砖', category: 'landmark', rarity: 'core', image: 'images/elements/beijing/beijing_06.png', tags: ['wall', 'historic', 'grey'] },
    { id: 'beijing_07', name: '故宫角楼', category: 'landmark', rarity: 'core', image: 'images/elements/beijing/beijing_07.png', tags: ['palace', 'golden', 'ancient'] },
    { id: 'beijing_08', name: '豆汁', category: 'food', rarity: 'core', image: 'images/elements/beijing/beijing_08.png', tags: ['drink', 'green', 'local'] },
    { id: 'beijing_09', name: '铜锣', category: 'item', rarity: 'core', image: 'images/elements/beijing/beijing_09.png', tags: ['instrument', 'golden', 'round'] },
    { id: 'beijing_10', name: '毛笔', category: 'item', rarity: 'core', image: 'images/elements/beijing/beijing_10.png', tags: ['writing', 'black', 'thin'] },
    { id: 'beijing_11', name: '鸟巢', category: 'landmark', rarity: 'core', image: 'images/elements/beijing/beijing_11.png', tags: ['stadium', 'modern', 'steel'] },
    { id: 'beijing_12', name: '冰糖葫芦', category: 'food', rarity: 'core', image: 'images/elements/beijing/beijing_12.png', tags: ['candy', 'stick', 'red'] },
    { id: 'beijing_13', name: '四合院门', category: 'culture', rarity: 'accent', image: 'images/elements/beijing/beijing_13.png', tags: ['door', 'red', 'traditional'] },
    { id: 'beijing_14', name: '景泰蓝', category: 'item', rarity: 'accent', image: 'images/elements/beijing/beijing_14.png', tags: ['craft', 'blue', 'enamel'] },
  ],
  levelPresets: [
    { id: 1, difficultyTier: 'intro',     seedBase: 11001, elementCount: 6,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.95, targetDurationSec: [60, 120] },
    { id: 2, difficultyTier: 'easy',      seedBase: 11002, elementCount: 7,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.90, targetDurationSec: [60, 120] },
    { id: 3, difficultyTier: 'normal',    seedBase: 11003, elementCount: 8,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.80, targetDurationSec: [90, 150] },
    { id: 4, difficultyTier: 'normal',    seedBase: 11004, elementCount: 9,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.70, targetDurationSec: [90, 150] },
    { id: 5, difficultyTier: 'hard',      seedBase: 11005, elementCount: 10, piecesPerElement: 3, layers: 4, density: 'medium_high', targetPassRate: 0.60, targetDurationSec: [120, 180] },
    { id: 6, difficultyTier: 'boss',      seedBase: 11006, elementCount: 10, piecesPerElement: [3,3,3,3,3,6,3,3,3,3], layers: 4, density: 'high', targetPassRate: 0.55, targetDurationSec: [120, 240] },
  ],
  shareCard: {
    titleUnlocked: '我解锁了北京猫！',
    titlePassport: '北京护照盖章完成',
  },
}
