module.exports = {
  id: 'istanbul',
  contentVersion: 1,
  continentId: 'asia',
  sortOrder: 6,
  unlockAfterCityId: 'singapore',
  bundle: {
    packId: 'asia-rest',
    preload: 'on-city-page',
  },
  display: {
    name: '伊斯坦布尔',
    nameEn: 'Istanbul',
    bgColor: '#1A5276',
    tagline: '博斯普鲁斯的猫',
    funFact: '伊斯坦布尔是唯一横跨两大洲的城市',
  },
  cover: {
    catImage: 'images/cats/cat_istanbul.png',
    catThumb: 'images/cats/cat_istanbul_thumb.png',
    shareAccent: '#E8D5B7',
  },
  cat: {
    id: 'cat_istanbul',
    name: '安安',
    intro: '佩戴恶魔之眼项圈的安哥拉猫，神秘优雅',
    baseColor: '#F5F5F5',
    pattern: 'solid',
    patternColor: '#E8E8E8',
    accessory: '恶魔之眼项圈',
    expression: 'mysterious',
  },
  passport: {
    stampId: 'stamp_istanbul',
    stampLabel: '伊斯坦布尔',
  },
  elements: [
    { id: 'istanbul_01', name: '蓝色清真寺', category: 'landmark', rarity: 'core', image: 'images/elements/istanbul/istanbul_01.png', tags: ['mosque', 'blue', 'dome'] },
    { id: 'istanbul_02', name: '土耳其红茶', category: 'food', rarity: 'core', image: 'images/elements/istanbul/istanbul_02.png', tags: ['tea', 'glass', 'red'] },
    { id: 'istanbul_03', name: '热气球', category: 'item', rarity: 'core', image: 'images/elements/istanbul/istanbul_03.png', tags: ['balloon', 'sky', 'colorful'] },
    { id: 'istanbul_04', name: '烤肉串', category: 'food', rarity: 'core', image: 'images/elements/istanbul/istanbul_04.png', tags: ['kebab', 'grill', 'meat'] },
    { id: 'istanbul_05', name: '郁金香', category: 'nature', rarity: 'core', image: 'images/elements/istanbul/istanbul_05.png', tags: ['flower', 'red', 'spring'] },
    { id: 'istanbul_06', name: '恶魔之眼', category: 'culture', rarity: 'core', image: 'images/elements/istanbul/istanbul_06.png', tags: ['amulet', 'blue', 'protection'] },
    { id: 'istanbul_07', name: '土耳其冰淇淋', category: 'food', rarity: 'core', image: 'images/elements/istanbul/istanbul_07.png', tags: ['dessert', 'stretchy', 'fun'] },
    { id: 'istanbul_08', name: '地毯', category: 'item', rarity: 'core', image: 'images/elements/istanbul/istanbul_08.png', tags: ['textile', 'pattern', 'woven'] },
    { id: 'istanbul_09', name: '石榴', category: 'nature', rarity: 'core', image: 'images/elements/istanbul/istanbul_09.png', tags: ['fruit', 'red', 'juicy'] },
    { id: 'istanbul_10', name: '旋转舞裙', category: 'culture', rarity: 'core', image: 'images/elements/istanbul/istanbul_10.png', tags: ['dance', 'whirl', 'white'] },
    { id: 'istanbul_11', name: '圣索菲亚', category: 'landmark', rarity: 'core', image: 'images/elements/istanbul/istanbul_11.png', tags: ['cathedral', 'dome', 'historic'] },
    { id: 'istanbul_12', name: '土耳其软糖', category: 'food', rarity: 'core', image: 'images/elements/istanbul/istanbul_12.png', tags: ['candy', 'sweet', 'colorful'] },
    { id: 'istanbul_13', name: '波斯猫雕像', category: 'culture', rarity: 'core', image: 'images/elements/istanbul/istanbul_13.png', tags: ['statue', 'cat', 'elegant'] },
    { id: 'istanbul_14', name: '香料', category: 'item', rarity: 'core', image: 'images/elements/istanbul/istanbul_14.png', tags: ['spice', 'bazaar', 'aromatic'] },
  ],
  levelPresets: [
    { id: 1, difficultyTier: 'intro',     seedBase: 16001, elementCount: 6,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.95, targetDurationSec: [60, 120] },
    { id: 2, difficultyTier: 'easy',      seedBase: 16002, elementCount: 7,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.90, targetDurationSec: [60, 120] },
    { id: 3, difficultyTier: 'normal',    seedBase: 16003, elementCount: 8,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.80, targetDurationSec: [90, 150] },
    { id: 4, difficultyTier: 'normal',    seedBase: 16004, elementCount: 9,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.70, targetDurationSec: [90, 150] },
    { id: 5, difficultyTier: 'hard',      seedBase: 16005, elementCount: 10, piecesPerElement: 3, layers: 4, density: 'medium_high', targetPassRate: 0.60, targetDurationSec: [120, 180] },
    { id: 6, difficultyTier: 'boss',      seedBase: 16006, elementCount: 10, piecesPerElement: [3,3,3,3,3,6,3,3,3,3], layers: 4, density: 'high', targetPassRate: 0.55, targetDurationSec: [120, 240] },
  ],
  shareCard: {
    titleUnlocked: '我解锁了伊斯坦布尔猫！',
    titlePassport: '伊斯坦布尔护照盖章完成',
  },
}
