module.exports = {
  id: 'seoul',
  contentVersion: 1,
  continentId: 'asia',
  sortOrder: 4,
  unlockAfterCityId: 'bangkok',
  bundle: {
    packId: 'asia-rest',
    preload: 'on-city-page',
  },
  display: {
    name: '首尔',
    nameEn: 'Seoul',
    bgColor: '#4A90D9',
    tagline: '景福宫前遇猫猫',
    funFact: '首尔的地铁系统覆盖率全球第一',
  },
  cover: {
    catImage: 'images/cats/cat_seoul.png',
    catThumb: 'images/cats/cat_seoul_thumb.png',
    shareAccent: '#F5E6CA',
  },
  cat: {
    id: 'cat_seoul',
    name: '韩韩',
    intro: '戴韩服小帽的韩国短尾猫，爱在景福宫前眨眼卖萌',
    baseColor: '#F5E6CA',
    pattern: 'bicolor',
    patternColor: '#D4A574',
    accessory: '韩服小帽',
    expression: 'wink',
  },
  passport: {
    stampId: 'stamp_seoul',
    stampLabel: '首尔',
  },
  elements: [
    { id: 'seoul_01', name: '泡菜坛', category: 'food', rarity: 'core', image: 'images/elements/seoul/seoul_01.png', tags: ['fermented', 'jar', 'red'] },
    { id: 'seoul_02', name: '石锅拌饭', category: 'food', rarity: 'core', image: 'images/elements/seoul/seoul_02.png', tags: ['rice', 'hot', 'colorful'] },
    { id: 'seoul_03', name: '韩服', category: 'culture', rarity: 'core', image: 'images/elements/seoul/seoul_03.png', tags: ['clothing', 'traditional', 'colorful'] },
    { id: 'seoul_04', name: '景福宫', category: 'landmark', rarity: 'core', image: 'images/elements/seoul/seoul_04.png', tags: ['palace', 'historic', 'grand'] },
    { id: 'seoul_05', name: '烧酒瓶', category: 'item', rarity: 'core', image: 'images/elements/seoul/seoul_05.png', tags: ['drink', 'green', 'bottle'] },
    { id: 'seoul_06', name: '年糕', category: 'food', rarity: 'core', image: 'images/elements/seoul/seoul_06.png', tags: ['sweet', 'chewy', 'white'] },
    { id: 'seoul_07', name: 'K-pop话筒', category: 'item', rarity: 'core', image: 'images/elements/seoul/seoul_07.png', tags: ['music', 'pop', 'shiny'] },
    { id: 'seoul_08', name: '太极旗扇', category: 'culture', rarity: 'core', image: 'images/elements/seoul/seoul_08.png', tags: ['flag', 'fan', 'national'] },
    { id: 'seoul_09', name: '韩式炸鸡', category: 'food', rarity: 'core', image: 'images/elements/seoul/seoul_09.png', tags: ['fried', 'crispy', 'golden'] },
    { id: 'seoul_10', name: '柿子', category: 'nature', rarity: 'core', image: 'images/elements/seoul/seoul_10.png', tags: ['fruit', 'orange', 'autumn'] },
    { id: 'seoul_11', name: '海苔卷', category: 'food', rarity: 'core', image: 'images/elements/seoul/seoul_11.png', tags: ['seaweed', 'roll', 'green'] },
    { id: 'seoul_12', name: '南山塔', category: 'landmark', rarity: 'core', image: 'images/elements/seoul/seoul_12.png', tags: ['tower', 'romantic', 'iconic'] },
    { id: 'seoul_13', name: '木槿花', category: 'nature', rarity: 'core', image: 'images/elements/seoul/seoul_13.png', tags: ['flower', 'pink', 'national'] },
  ],
  levelPresets: [
    { id: 1, difficultyTier: 'intro',     seedBase: 14001, elementCount: 6,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.95, targetDurationSec: [60, 120] },
    { id: 2, difficultyTier: 'easy',      seedBase: 14002, elementCount: 7,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.90, targetDurationSec: [60, 120] },
    { id: 3, difficultyTier: 'normal',    seedBase: 14003, elementCount: 8,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.80, targetDurationSec: [90, 150] },
    { id: 4, difficultyTier: 'normal',    seedBase: 14004, elementCount: 9,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.70, targetDurationSec: [90, 150] },
    { id: 5, difficultyTier: 'hard',      seedBase: 14005, elementCount: 10, piecesPerElement: 3, layers: 4, density: 'medium_high', targetPassRate: 0.60, targetDurationSec: [120, 180] },
    { id: 6, difficultyTier: 'boss',      seedBase: 14006, elementCount: 10, piecesPerElement: [3,3,3,3,3,6,3,3,3,3], layers: 4, density: 'high', targetPassRate: 0.55, targetDurationSec: [120, 240] },
  ],
  shareCard: {
    titleUnlocked: '我解锁了首尔猫！',
    titlePassport: '首尔护照盖章完成',
  },
}
