module.exports = {
  id: 'tokyo',
  contentVersion: 1,
  continentId: 'asia',
  sortOrder: 2,
  unlockAfterCityId: 'beijing',
  bundle: {
    packId: 'asia-rest',
    preload: 'on-city-page',
  },
  display: {
    name: '东京',
    nameEn: 'Tokyo',
    bgColor: '#E84057',
    tagline: '东京タワー下的喵',
    funFact: '东京的铁路网是世界上最密集的',
  },
  cover: {
    catImage: 'images/cats/cat_tokyo.png',
    catThumb: 'images/cats/cat_tokyo_thumb.png',
    shareAccent: '#FFB7C5',
  },
  cat: {
    id: 'cat_tokyo',
    name: '樱樱',
    intro: '戴着招财猫铃铛的白猫，喜欢在樱花树下打盹',
    baseColor: '#FFFFFF',
    pattern: 'solid',
    patternColor: '#F5F5F5',
    accessory: '招财猫铃铛',
    expression: 'wink',
  },
  passport: {
    stampId: 'stamp_tokyo',
    stampLabel: '东京',
  },
  elements: [
    { id: 'tokyo_01', name: '寿司', category: 'food', rarity: 'core', image: 'images/elements/tokyo/tokyo_01.png', tags: ['fish', 'rice', 'fresh'] },
    { id: 'tokyo_02', name: '招财猫', category: 'culture', rarity: 'core', image: 'images/elements/tokyo/tokyo_02.png', tags: ['lucky', 'cat', 'golden'] },
    { id: 'tokyo_03', name: '富士山', category: 'landmark', rarity: 'core', image: 'images/elements/tokyo/tokyo_03.png', tags: ['mountain', 'snow', 'iconic'] },
    { id: 'tokyo_04', name: '樱花', category: 'nature', rarity: 'core', image: 'images/elements/tokyo/tokyo_04.png', tags: ['flower', 'pink', 'spring'] },
    { id: 'tokyo_05', name: '鸟居', category: 'landmark', rarity: 'core', image: 'images/elements/tokyo/tokyo_05.png', tags: ['gate', 'red', 'shrine'] },
    { id: 'tokyo_06', name: '拉面', category: 'food', rarity: 'core', image: 'images/elements/tokyo/tokyo_06.png', tags: ['noodle', 'hot', 'bowl'] },
    { id: 'tokyo_07', name: '抹茶', category: 'food', rarity: 'core', image: 'images/elements/tokyo/tokyo_07.png', tags: ['tea', 'green', 'powder'] },
    { id: 'tokyo_08', name: '浮世绘', category: 'culture', rarity: 'core', image: 'images/elements/tokyo/tokyo_08.png', tags: ['art', 'wave', 'woodblock'] },
    { id: 'tokyo_09', name: '新干线', category: 'item', rarity: 'core', image: 'images/elements/tokyo/tokyo_09.png', tags: ['train', 'fast', 'white'] },
    { id: 'tokyo_10', name: '达摩', category: 'culture', rarity: 'core', image: 'images/elements/tokyo/tokyo_10.png', tags: ['doll', 'red', 'wish'] },
    { id: 'tokyo_11', name: '和服扇', category: 'item', rarity: 'core', image: 'images/elements/tokyo/tokyo_11.png', tags: ['fan', 'elegant', 'pattern'] },
    { id: 'tokyo_12', name: '章鱼烧', category: 'food', rarity: 'core', image: 'images/elements/tokyo/tokyo_12.png', tags: ['octopus', 'ball', 'street-food'] },
    { id: 'tokyo_13', name: '东京塔', category: 'landmark', rarity: 'accent', image: 'images/elements/tokyo/tokyo_13.png', tags: ['tower', 'orange', 'night'] },
    { id: 'tokyo_14', name: '柴犬', category: 'nature', rarity: 'accent', image: 'images/elements/tokyo/tokyo_14.png', tags: ['dog', 'cute', 'fluffy'] },
  ],
  levelPresets: [
    { id: 1, difficultyTier: 'intro',     seedBase: 12001, elementCount: 6,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.95, targetDurationSec: [60, 120] },
    { id: 2, difficultyTier: 'easy',      seedBase: 12002, elementCount: 7,  piecesPerElement: 3, layers: 2, density: 'low',         targetPassRate: 0.90, targetDurationSec: [60, 120] },
    { id: 3, difficultyTier: 'normal',    seedBase: 12003, elementCount: 8,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.80, targetDurationSec: [90, 150] },
    { id: 4, difficultyTier: 'normal',    seedBase: 12004, elementCount: 9,  piecesPerElement: 3, layers: 3, density: 'medium',      targetPassRate: 0.70, targetDurationSec: [90, 150] },
    { id: 5, difficultyTier: 'hard',      seedBase: 12005, elementCount: 10, piecesPerElement: 3, layers: 4, density: 'medium_high', targetPassRate: 0.60, targetDurationSec: [120, 180] },
    { id: 6, difficultyTier: 'boss',      seedBase: 12006, elementCount: 10, piecesPerElement: [3,3,3,3,3,6,3,3,3,3], layers: 4, density: 'high', targetPassRate: 0.55, targetDurationSec: [120, 240] },
  ],
  shareCard: {
    titleUnlocked: '我解锁了东京猫！',
    titlePassport: '东京护照盖章完成',
  },
}
